# Setup
title:               imdua
tagline:             '스터디 메모장'
description:         ''
url:                 https://imdua.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yoon Yeom
  url:               https://github.com/imdua
  email:             yoon.yeom.dev@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

remote_theme: lanyon
